### PR TITLE
Added CI

### PR DESCRIPTION
**Pull request by charettes**

### CODE REVIEW

**Comment by charettes** [comment]
@camilonova could you please enable TravisCI for this repo, I'm missing administrative rights.

**Comment by camilonova** [comment]
@jezdez Seems you are the one who can enable it.

**Comment by jezdez** [comment]
@camilonova sure, please file a bug in the roadies repo next time :)

**Comment by jezdez** [comment]
:+1: done

**Comment by camilonova** [comment]
Thanks

**Pull request merged**
